
server:
    static_dir: 'static'

storage:
    storage_type: '',
    region_name: '',
    endpoint_url: '',
    access_key_id: '',
    secret_access_key: '',
    bucket: ''
    base_dir: ''

api_clients:
    base: 'https://<api_url>'
    version: '<version>'
    lang: en
    token: <token>
    user: <user_id>
    user_info_fields:
        - first_name
        - last_name
        - verified
        - sex
        - bdate
        - city
        - country
        - home_town
        - has_photo
        - photo_max_orig
        - domain
        - has_mobile
        - contacts
        - site
        - status
        - nickname
        - about

    group_info_fields:
        - city
        - contacts
        - counters
        - country
        - description
        - main_album_id
